enc:
  key: "![jiStGO29MyY=]"
  algorithm: "![SVM+dMU4kJkLYPx1FAuJ3w==]"
  mode: "![EmRDUufWylA=]"

extidpnfo:
  authkey: "![fumtN3XDl3r5lUzNJF9q/Osz4TfFM+3lR2f2slZ+EW8+WtqvtpyGVaKKlXlORavT]"
  url: velobank.oktapreview.com

