#%RAML 1.0
title: okta-api-setup-test-v2
description:  An orchestrated process API to setup a customer profiles for Authentication and MFA verification on Okta.

baseUri: https://devopenapi.velobank.com/api/prc/v1/usermgmt/

types:
  UserSetupRequestClient: !include resources/user-setup-types-client.raml
  UserActivateRequestclient: !include resources/user-activation-types-client.raml
  UserChallengeRequestClient: !include resources/okta-challenge-types.raml
  UserVerifyRequestClient: !include resources/okta-verify-types.raml

traits:
  VerificationInfo: !include resources/okta-user-setup-traits.raml

/user:
  post:
    description: Used to setup user 
    is: [VerificationInfo]
    body:
      application/json:
        type: UserSetupRequestClient
        example: !include examples/create-user-request-client.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/create-user-response-client.json
     
      400:
        body:
          application/json:
            examples:
              UserLoginMissing: !include errors/create-error-res-login-missing.json
              UserEmailMissing: !include errors/create-error-res-email-missing.json
              UserExists: !include errors/create-error-res-user-exists.json
              UserInputMiss: !include errors/create-error-res-missing-req-input.json


  get:
    description: Used to search users based on query params
    queryParameters:
      loginId:
        type: string
        required: false
      email:
        type: string
        required: false
      phoneNum:
        type: string
        required: false

    is: [VerificationInfo]
    responses:
      200:
        body:
          application/json:
            examples: 
              SearchWithResults: !include examples/search-user-response-with-result-client.json
              SearchWithNoResults: !include examples/search-user-response-with-no-result-client.json
      400:
        body:
          application/json:
            examples: 
              GenericError: !include errors/error-response.json
              BadSearchFilter: !include errors/search-error-res-bad-search.json
              
  put:
    description: Used to activate user with password
    is: [VerificationInfo]
    body:
      application/json:
        type: UserActivateRequestclient
        example: !include examples/activate-user-request-client.json
    responses:
      200:
        body:
            application/json:
                example: !include examples/activate-user-response-client.json
      400:
        body:
          application/json:
              examples: 
                GenericError: !include /errors/error-response.json
                InvalidPwdError: !include /errors/update-pwd-error-res-pwd-rules.json


  /sendOTP:
    description: Used to initiate OTP
    post:
      
      description: Same method to handle challge and verify
      is: [VerificationInfo]
      body:
        application/json:
          type: UserChallengeRequestClient
          example: !include examples/challenge-factor-request-client.json
      responses:
        200:
          body:
              application/json:
                  example: !include examples/challenge-factor-response-client.json
        400:
          body:
            application/json:
                examples: 
                  GenericError: !include errors/error-response.json
                  CodeAlreadySent : !include errors/challenge-code-recent-sent.json
                  BlankFacInput: !include errors/challenge-error-res-missing-fac.json
                  MissingProfileInput: !include errors/challenge-error-res-missing-profile.json
                  NoFactorInput: !include errors/challenge-error-res-no-fac-type.json

  /verifyOTP:
    description: Used to verify OTP
    post:
      
      description: Same method to handle challge and verify
      is: [VerificationInfo]
      body:
        application/json:
          type: UserVerifyRequestClient
          example: !include examples/verify-factor-request-client.json
      responses:
        200:
          body:
              application/json:
                  example: !include examples/verify-factor-res-client.json
        400:
          body:
            application/json:
                examples: 
                  GenericError: !include errors/error-response.json
                  InvalidPassCode: !include errors/verify-error-code-invalid.json
                  InvalidUser: !include errors/verify-error-user-invalid.json